name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.Js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Install dependencies
        run: |
          npm install --omit=dev
          tar -a -c -f MTG-Card-Search-${{steps.version.outputs.prop}}.zip --exclude .git* --exclude *.zip --exclude cache --exclude history --exclude node_modules/.cache *
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: 'MTG-Card-Search-${{steps.version.outputs.prop}}.zip'
          tag_name: 'v${{steps.version.outputs.prop}}'
